#+TITLE: QTILE DESKTOP CONFIG
#+AUTHOR: Cesar Leon
#+EMAIL: leoncesaralejandro@gmail.com
#+DESCRIPTION: Qtile desktop environment
#+DATE: <2021-09-08 Wed>

* Table of Contents :toc:
- [[#what-is-this][What is this?]]
  - [[#features][Features]]
- [[#software-used][Software used]]
  - [[#display-server][Display Server]]
  - [[#folder-management][Folder management]]
  - [[#window-manager-and-stuff][Window Manager and stuff]]
  - [[#fonts][Fonts]]
  - [[#other-software][Other software]]
- [[#important][Important]]
- [[#screenshots][Screenshots]]

* What is this?
A Qtile config file with a "minimalistic" (because now everything with less clutter is minimalistic), using a proper arrangement of windows and *almost* a proper usage of python features to make the config readable to the user.

** Features
 - Top bar, instead of the default bottom bar.
 - Icons for every widget that could be iconized.
 - Window arrangement with the primary goal of displaying a beautiful and cool wallpaper.
 - Default qtile config features already optimized.

* Software used
Throughout the configuration file, you will encounter with variables, arrays, dictionaries and other stuff that maybe, just maybe, it is not installed in your Distro.

This config assumes that you run a vanilla Arch Linux (just the tty terminal with bash or zsh) OS. If you're using other distros like Debian, consult your package manager for packages availability.

This config has not been used alongside these KDE, LXDE or GNOME; so I can't give support for multiple DE (I have a simple XMonad environment, but it didn't give me problems or crashes).

Here is the list of the software currently used to run Qtile with this config. This list is arranged in order of installation (as i remember), and gives you the steps I used to reach this environment.

** Display Server
 - [[https://xorg.freedesktop.org][Xorg display server]]

   I use Xorg display server as default. Haven't tested the config with others. Install all the group and all its dependencies.

** Folder management
 - [[https://www.freedesktop.org/wiki/Software/xdg-ser-dirs][xdg-user-dirs & xdg-utils]]

   These packages are used to create simple directories and the .config and .local folders to store dotfiles and other configs.

   You can use other software that manages your dotfiles. The default for packages like picom and qtile is to create a dotfolder in tyour home directory (~/.picom or/and $HOME/.qtile). Do as you like.

   In my case, I use these folders as default storage of config files, including Qtile config and fonts (next topic).

 - [[https://github.com/alacritty/alacritty][Alacritty]]

   I've been using Alacritty, and it is really fast, but you can use the terminal emulator of your liking.

** Window Manager and stuff
 - [[https://www.qtile.org][Qtile]]

   Obviously.

 - [[https://github.com/yshui/picom][picom]]

   The compositor to create fade effects, opacity and other stuff.

 - [[http://projects.l3ib.org/nitrogen][nitrogen]]

   Wallpaper browser (JUST THE BROWSER). You need to download your wallpapers in order to use it, as you will only find a black screen at startup and an empty white space in nitrogen.

 - [[https://www.brave.com][Brave browser]]

   A Chromium based browser with added functionality and less CPU/Memory consumption, not like the other Chromium based browser (the big corporation one).

** Fonts

This topic is important if you want to use icons and glyphs instead of words to label your groups (workspaces) or to give more flavor to simple things like the hour or the net usage.

Install any NerdFont patched Font from [[https://github.com/ryanoasis/nerd-fonts/][ryanoasis/nerd-fonts]] in ~.local/share/fonts~ folder or your preferred fonts folder, run ~fc-cache -vf~ and see if it's available with ~fc-list | grep "$YOUR_FONT"~ /where/ ~YOUR_FONT~ is the name of the downloaded patched font.

Test the font with your qtile config by copying the icon from the [[https://www.nerdfonts.com/cheat-sheet][Cheat Sheet]] to, for instance, the "Bar" object, test your config.py file, solve any errors and restart qtile when everything's ok.

You should see the icon instead of a white border empty rectangle. The fonts used in this config are:

 - NotoSansMono Nerd Font
 - SauceCodePro Nerd Font

** Other software

There are other apps/packages installed on the OS and used in the config. It is up to you to install them on the systen or removing them from the config.

* Important
Be aware to backup your file before attempting to modify the config. I've spent hours with errors just because there wasn't a comma in one of the lists, and I don't want you to suffer the same.

A good measure to avoid this is to have an IDE capable of debugging, that way you can trace errors and solve them easily.

* Screenshots
